--////////////////////////////////////////////////
--VERSÃO 2
SELECT DISTINCT M.CD_MATERIAL AS "CONT.COD CONTROLADOR"
, M.CD_SISTEMA_ANT AS "CONT. COD SISTEMA ANTERIOR"
, M.DS_MATERIAL AS "CONT. MATERIAL"
, M.DS_REDUZIDA AS "CONT. DESC REDUZIDA"
, M.CD_MATERIAL_GENERICO
, M.IE_VIA_APLICACAO "CONT. VIA APLICAÇÃO"
--, M.IE_TIPO_MATERIAL
--, RMA.IE_TIPO_MATERIAL_CONSIDERAR
, M.NR_SEQ_FICHA_TECNICA AS "CONT. FICHA TEC"
, RMA.IE_TIPO_MATERIAL_CONSIDERAR
, substr(obter_valor_dominio(29,RMA.IE_TIPO_MATERIAL_CONSIDERAR),1,40) AS "RMA DESC TIPO MATERIAL"
, RMA.CD_CONVENIO AS "RMA CONVÊNIO"
, substr(Obter_Nome_Convenio(RMA.CD_CONVENIO),1,255) AS "RMA CONVÊNIO"
--, RMA.CD_ESTABELECIMENTO AS "RMA ESTABELECIMENTO"
, substr(obter_nome_estabelecimento(RMA.cd_estabelecimento),1,60) AS "RMA ESTABELECIMENTO"
--, RMA.IE_TIPO_MATERIAL_CONSIDERAR AS "RMA Tipo de material"
--, MAT.CD_MATERIAL AS "COD MATERIAL"
--, MAT.DS_MATERIAL
--, MAT.CD_SISTEMA_ANT AS "COD PROTHEUS"
--, MAT.IE_PRESCRICAO AS "PRESC PARA O ESTABELECIMENTO"
--, MAT.IE_TIPO_MATERIAL
--, substr(obter_valor_dominio(29,MAT.IE_TIPO_MATERIAL),1,40) AS "CAD MATERIAS TIPO MATERIAL"
, FICHA.CD_MATERIAL AS "MATERIAL COD"
, FICHA.NR_SEQ_FICHA_TECNICA AS "MATERIAL FICHA TECNICA"
, FICHA.CD_SISTEMA_ANT AS "MATERIAL PROTHEUS"
, FICHA.DS_REDUZIDA AS "MATERIAL"
, FICHA.IE_VIA_APLICACAO AS "MATERIAL VIA APLICAÇÃO"
, FICHA.IE_TIPO_MATERIAL AS "TIPO MATERIAL"
, substr(obter_valor_dominio(29,FICHA.IE_TIPO_MATERIAL),1,40) AS "MATERIAL TIPO MATERIAL"
, ME.IE_PRESCRICAO AS "FLAG PRESCRIÇÃO POR FILIAL"
, CASE
WHEN M.IE_VIA_APLICACAO <> FICHA.IE_VIA_APLICACAO THEN 'INCONSISTENTE'
WHEN M.IE_VIA_APLICACAO IS NULL THEN 'VIA NO CONTROLADOR NÃO PREENCHIDA'
WHEN FICHA.IE_VIA_APLICACAO IS NULL THEN 'VIA NO MED ESTOQUE NÃO PREENCHIDA'
ELSE 'OK' END AS "INCONSISTÊNCIA: VIA APLICAÇÃO"
, CASE
WHEN RMA.IE_TIPO_MATERIAL_CONSIDERAR <> FICHA.IE_TIPO_MATERIAL THEN 'INCONSISTENTE'
ELSE 'OK' END AS "INCONSISTÊNCIA: TIPO MATERIAL"
-- CASO QUEIRA CONFIRMAR O ESTABELECIMENTO E UNIDADE DO WHERE, SÓ TIRAR O COMENTÁRIO DAS LINHAS ABAIXO
--, RMA.CD_ESTABELECIMENTO
--, substr(obter_nome_estabelecimento(RMA.cd_estabelecimento),1,60) AS "RMA ESTABELECIMENTO"
--, ME.CD_ESTABELECIMENTO
--, substr(obter_nome_estabelecimento(ME.CD_ESTABELECIMENTO),1,60) AS "RMA ESTABELECIMENTO"
--, RMA.CD_CONVENIO
--, substr(Obter_Nome_Convenio(RMA.CD_CONVENIO),1,255) AS "RMA CONVÊNIO"

FROM MATERIAL M
LEFT JOIN REGRA_APRESENTACAO_QUIMIO RMA
ON M.CD_MATERIAL = RMA.CD_MATERIAL
LEFT JOIN MATERIAL FICHA
ON M.NR_SEQ_FICHA_TECNICA = FICHA.NR_SEQ_FICHA_TECNICA
LEFT JOIN MATERIAL_ESTAB ME
ON FICHA.CD_MATERIAL = ME.CD_MATERIAL
--LEFT JOIN MATERIAL MAT
--ON MAT.CD_MATERIAL_GENERICO = RMA.CD_MATERIAL
WHERE M.CD_MATERIAL IN (91430) --90118
--90113, 85264 NÃO LOCALIZADA RMA
--M.DS_MATERIAL LIKE '%platina%' AND
--RMA.CD_CONVENIO = 5
--AND
AND RMA.CD_ESTABELECIMENTO = 51
AND ME.CD_ESTABELECIMENTO = 51
AND FICHA.IE_SITUACAO <> 'I'
AND FICHA.CD_SISTEMA_ANT <> 0000
AND ME.IE_PRESCRICAO = 'S'
AND RMA.IE_TIPO_MATERIAL_CONSIDERAR = FICHA.IE_TIPO_MATERIAL
ORDER BY 10, 1, 7, 9, 8, 16, 19;

